using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;

public class testUI : MonoBehaviour
{
    public BubbleSort bubbleSort;
    public BubbleSort startBubbleSort;
    public SortingAlgorithm cubes;
    public InputField inputNumCubes;
    public void startSort()
    {
        startBubbleSort = Instantiate(bubbleSort);
        startBubbleSort.setup(Convert.ToInt32(inputNumCubes.text));
        //startBubbleSort.sort();
    }
    public void stopSort()
    {
        
    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
